on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        run: |
          shellcheck -x juvix-installer.sh
          cd test
          shellcheck -x stub_test.sh

      - name: install shells
        run: |
          brew install fish
          brew install zsh

      - name: stub test juvix-installer
        shell: bash
        run: |
          cd test
          ./stub_test.sh

      - name: test juvix-installer
        run: |
          cd test
          ./test.sh

      - name: run juvix-installer with -y
        run: |
          ./juvix-installer.sh -y

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: install shells
        run: |
          brew install fish
          brew install zsh

      - name: stub test juvix-installer
        shell: bash
        run: |
          cd test
          ./stub_test.sh

      - name: test juvix-installer
        run: |
          cd test
          ./test.sh

      - name: run juvix-installer with -y
        run: |
          ./juvix-installer.sh -y
